### ISSUE TITLE
Cannot read property 'apply' of undefined hatası ile karşılaşıyorum 

### ISSUE THREAD

**Issue by abdurrahmanekr** [alpcanaydin/tepsi.co#5]
Projeyi kurduktan sonra `npm i` komutunu çalıştırıyorum. sonra `npm start` diyorum. Tarayıcıda bu hata ile karşılaşıyorum. Başka bir kurulum mu yapmam gerekiyor yoksa bir bağımlılık hatası mı? Bu konuda yardım edebilir misiniz? 
edit: 
<img width="677" alt="ekran resmi 2017-07-30 os 1 04 54" src="https://user-images.githubusercontent.com/15075759/28752441-fd67138e-7527-11e7-9202-19bf9e39d4b1.png">

**Comment by abdurrahmanekr** [comment]
Sorunu buldum. [Burada](https://github.com/alpcanaydin/tepsi.co/blob/82ddc054b62f1989af544f36cc60a6caeac4469d/src/redux/configureStore.js#L21) zorunlu olarak geliştiricinin `__REDUX_DEVTOOLS_EXTENSION__` içeren değişkeni composed sabitine push etmesi gerekiyor. Bu sorunu şöyle çözüyorum:
```javascript
var devExtension = window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__();
if (devExtension)
    composed.push(devExtension);
```
Eğer devExtension varsa composed üzerine push edecek, böylelikle sorun çözülüyor. İsterseniz bir PR atabilirim.

**Comment by alpcanaydin** [comment]
Merhaba,

Teşekkürler bildirim için, eğer PR gönderebilirsen kabul edebilirim.
