### ISSUE TITLE
Unknown DOM property class. Did you mean className?

### ISSUE THREAD

**Issue by ahmetozalp** [alpcanaydin/tepsi.co#7]
Tepsi.CO'da kullandıgın kodları geliştiriyorumda geliştirirken hata degil ama uyarı var bunu kapatmak için bir kaynak bulamadım bakaiblirmisin

> warning.js:35 Warning: Unknown DOM property class. Did you mean className?
>     in header (at Header.js:5)
>     in Header (at App.js:13)
>     in div (at App.js:12)
>     in App (at index.js:22)
>     in Router (created by ConnectedRouter)
>     in ConnectedRouter (at index.js:21)
>     in Provider (at index.js:20)

header.css ve footer.css gibi kodları kaldırdım gobal bir app.css içinden işlem yapıyorum

**Comment by alpcanaydin** [comment]
Header.js'te `className` yerine `class` yazılmış. Onu düzeltirsen hallolacaktır.

**Comment by ahmetozalp** [comment]
Gözümden kaçmış harikasın
